name: tabitabi_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  provider: ^4.3.2+2
  flutter_datetime_picker: ^1.3.8
  bubble: ^1.1.9+1
  flutter_dotenv: ^2.1.0
  google_maps_flutter: ^1.0.3
  location: ^3.0.2
  flutter_google_places: 0.2.6
  google_maps_webservice: ^0.0.18
  page_transition: ^1.1.7+2
  sliding_sheet: ^0.4.1
  like_button: ^1.0.4
  flutter_rating_bar: ^3.2.0
  permission_handler: ^5.0.1+1
  intl: ^0.16.1
  shared_preferences: ^0.5.12+4
  http: ^0.12.2
  image_picker: ^0.6.7+17
  smart_select: ^4.3.2
  flutter_slidable: ^0.5.7
  qr_flutter: ^3.2.0
  qr_code_scanner: ^0.2.1
  google_directions_api: ^0.5.0
  modal_bottom_sheet: ^1.0.0+1
  aws_s3: ^0.1.1+hotfix.5
  amazon_s3_cognito:
    git:
      url: https://github.com/opqrstuvcut/amazon_s3_cognito
  multi_image_picker: ^4.7.14
  flutter_absolute_path: ^1.0.6
  flutter_image_compress: ^0.7.0
  path_provider: ^1.6.27
  image_gallery_saver: ^1.6.7
  firebase_dynamic_links: ^0.7.0+1
  share: ^0.6.5+4
  fluttertoast: ^7.1.6
  sliding_up_panel: ^1.0.2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
#  firebase_crashlytics: ^0.4.0+1
  firebase_ml_vision: ^0.10.0
  firebase_analytics: ^7.0.1
  esys_flutter_share: ^1.0.2
  google_fonts: ^1.1.2
  flutter_native_splash: ^0.2.9
  cached_network_image: ^2.5.0
  get_it: ^5.0.6

flutter_native_splash:
  image: "images/logo.png"
  color: "ffffff"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - .env
    - json/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.


  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
